version: '3.4'

services:
  notificationserviceapi:
    image: ${DOCKER_REGISTRY-}notificationserviceapi
    build:
      context: .
      dockerfile: src/services/notification/NotificationServiceAPI/Dockerfile

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb-container
    command: mongod --auth --bind_ip_all
    environment:
      MONGO_INITDB_DATABASE: NotificationStore
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
  
  rabbit:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmqhost    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

 
  authservice_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  authservice_webapi:
    image: auth/webapi
    build:
      context: .
      dockerfile: src/services/auth/webapi/Dockerfile
    ports:
      - "8090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultPostgresConnection=Host=authservice_db;Port=5432;Database=postgres;Username=postgres;Password=123456
    depends_on:
      - authservice_db

volumes:
  mongodb-data:
    driver: local  
  postgres_data:

